### ISSUE TITLE
Alot of bugs...

### ISSUE THREAD

**Issue by marcus1810** [andrewtheis/prophunt#18]
1. If you have pointshop with the new prophunt, the playermodels still shows when you are a prop: http://gyazo.com/20119df32879d4e972fc2c477f8dde7a

2. there is a purple thing at the props feet that the hunters can see

3. the props are delayed, so when you jump the camera jumps first, then the prop jumps afterwards

4. the props are delayed when moving any direction, this makes it difficult to move anywhere, aspecially when the prop is so delayed that it goes behind the camera while moving forward.

What i really like about this new prophunt release is the rotation of the props.

**Comment by msburgess3200** [comment]
To add onto you list...
5. When you are a hunter and die and press 'spacebar' you respawn.
6. Removed Crowbar from weapons list.


About #6 if you want to add a crowbar manually edit /gamemodes/prophunt/gamemodes/player_class/player_hunter.lua

On line 35 find: 	self.Player:Give("weapon_shotgun")
 Before, add: self.Player:Give("weapon_crowbar")

Save, upload, restart server and you're done.

**Comment by andrewtheis** [comment]
1&2. I can't fix bugs that are caused by other add ons.
3&4. Issue with Source engine / Garry's Mod.

@msburgess3200 Please open separate bugs for those issues.
